In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier

In [2]:
df = pd.read_csv("Projects_Report.csv")
# x=df.iloc[:, :-1]
# y=df.iloc[:, :-1]

In [3]:
df.head

<bound method NDFrame.head of       Sr. No.                         Sector Name  \
0           1  Aviation & Aviation Infrastructure
1           2  Aviation & Aviation Infrastructure
2           3  Aviation & Aviation Infrastructure
3           4  Aviation & Aviation Infrastructure
4           5  Aviation & Aviation Infrastructure
...       ...                                 ...
1770     1771                     Water Resources
1771     1772                     Water Resources
1772     1773                     Water Resources
1773     1774                     Water Resources
1774     1775                     Water Resources

                                          Line Ministry  \
0                            Ministry of Civil Aviation
1                            Ministry of Civil Aviation
2                            Ministry of Civil Aviation
3                            Ministry of Civil Aviation
4                            Ministry of Civil Aviation
...                                                 ...
1770  Department of Water Resources, River Developme...
1771  Department of Water Resources, River Developme...
1772  Department of Water Resources, River Developme...
1773  Department of Water Resources, River Developme...
1774  Department of Water Resources, River Developme...

                                    Implementing Agency  Project Code  \
0                      Airport Authority of India [AAI]        706718
1                      Airport Authority of India [AAI]        701121
2                      Airport Authority of India [AAI]        701101
3                      Airport Authority of India [AAI]        612788
4                      Airport Authority of India [AAI]        612787
...                                                 ...           ...
1770                   Department of Water Resources-JH        701376
1771  Department of Water Resources, River Developme...        701402
1772                      Water Resources Department-MN        701400
1773                                 Water Resources-KA        701377
1774              Department of water resources-MH - II        701383

                                           Project Name  \
0                               C/o NITB Imphal Airport
1     Construction of New Domestic Terminal Building...
2     Construction of New Domestic Terminal Building...
3     Construction of New Domestic Terminal Building...
4     Construction of New Domestic Terminal Building...
...                                                 ...
1770       Subernarekha Multipurpose Project, Jharkhand
1771                       Subernarekha Project, Odisha
1772                       Thoubal Multipurpose Project
1773                     Upper Tunga Irrigation Project
1774                                     Waghur Project

      Original Cost\n(in cr.)  Revised Cost\n(in cr.)  Expenditure\n(in cr.)  \
0                         499                  499.00                 212.17
1                         347                    0.00                 189.48
2                        1217                 1216.90                1203.48
3                         322                    0.00                 240.99
4                         320                    0.00                 169.11
...                       ...                     ...                    ...
1770                     3808                 9579.58                6040.27
1771                     3056                 7023.19                8327.62
1772                     1449                 1822.24                1848.17
1773                      770                 1606.07                1515.60
1774                     1059                 1758.51                1642.50

      Physical Progress\n(in %) Original\nDate of Commissioning  \
0                            53                      13-07-2024
1                            96                      13-08-2025
2                            99                      31-05-2026
3                            97                      01-02-2026
4                            88                      21-01-2026
...                         ...                             ...
1770                         70                      31-12-2019
1771                         96                      31-12-2019
1772                         99                      31-12-2019
1773                         99                      31-12-2019
1774                         90                      31-12-2019

     Revised\nDate of Commissioning Sanction Date
0                        31-12-2026    01-11-2021
1                        25-08-2026    30-12-2022
2                        31-08-2026    04-10-2018
3                        31-08-2026    02-06-2023
4                        30-09-2026    02-06-2023
...                             ...           ...
1770                     31-03-2026    01-04-2011
1771                     31-03-2026    28-12-1995
1772                     31-12-2026    01-04-1997
1773                     31-03-2026    01-04-2014
1774                     31-03-2026    01-04-1996

[1775 rows x 13 columns]>

In [4]:
df.info

<bound method DataFrame.info of       Sr. No.                         Sector Name  \
0           1  Aviation & Aviation Infrastructure
1           2  Aviation & Aviation Infrastructure
2           3  Aviation & Aviation Infrastructure
3           4  Aviation & Aviation Infrastructure
4           5  Aviation & Aviation Infrastructure
...       ...                                 ...
1770     1771                     Water Resources
1771     1772                     Water Resources
1772     1773                     Water Resources
1773     1774                     Water Resources
1774     1775                     Water Resources

                                          Line Ministry  \
0                            Ministry of Civil Aviation
1                            Ministry of Civil Aviation
2                            Ministry of Civil Aviation
3                            Ministry of Civil Aviation
4                            Ministry of Civil Aviation
...                                                 ...
1770  Department of Water Resources, River Developme...
1771  Department of Water Resources, River Developme...
1772  Department of Water Resources, River Developme...
1773  Department of Water Resources, River Developme...
1774  Department of Water Resources, River Developme...

                                    Implementing Agency  Project Code  \
0                      Airport Authority of India [AAI]        706718
1                      Airport Authority of India [AAI]        701121
2                      Airport Authority of India [AAI]        701101
3                      Airport Authority of India [AAI]        612788
4                      Airport Authority of India [AAI]        612787
...                                                 ...           ...
1770                   Department of Water Resources-JH        701376
1771  Department of Water Resources, River Developme...        701402
1772                      Water Resources Department-MN        701400
1773                                 Water Resources-KA        701377
1774              Department of water resources-MH - II        701383

                                           Project Name  \
0                               C/o NITB Imphal Airport
1     Construction of New Domestic Terminal Building...
2     Construction of New Domestic Terminal Building...
3     Construction of New Domestic Terminal Building...
4     Construction of New Domestic Terminal Building...
...                                                 ...
1770       Subernarekha Multipurpose Project, Jharkhand
1771                       Subernarekha Project, Odisha
1772                       Thoubal Multipurpose Project
1773                     Upper Tunga Irrigation Project
1774                                     Waghur Project

      Original Cost\n(in cr.)  Revised Cost\n(in cr.)  Expenditure\n(in cr.)  \
0                         499                  499.00                 212.17
1                         347                    0.00                 189.48
2                        1217                 1216.90                1203.48
3                         322                    0.00                 240.99
4                         320                    0.00                 169.11
...                       ...                     ...                    ...
1770                     3808                 9579.58                6040.27
1771                     3056                 7023.19                8327.62
1772                     1449                 1822.24                1848.17
1773                      770                 1606.07                1515.60
1774                     1059                 1758.51                1642.50

      Physical Progress\n(in %) Original\nDate of Commissioning  \
0                            53                      13-07-2024
1                            96                      13-08-2025
2                            99                      31-05-2026
3                            97                      01-02-2026
4                            88                      21-01-2026
...                         ...                             ...
1770                         70                      31-12-2019
1771                         96                      31-12-2019
1772                         99                      31-12-2019
1773                         99                      31-12-2019
1774                         90                      31-12-2019

     Revised\nDate of Commissioning Sanction Date
0                        31-12-2026    01-11-2021
1                        25-08-2026    30-12-2022
2                        31-08-2026    04-10-2018
3                        31-08-2026    02-06-2023
4                        30-09-2026    02-06-2023
...                             ...           ...
1770                     31-03-2026    01-04-2011
1771                     31-03-2026    28-12-1995
1772                     31-12-2026    01-04-1997
1773                     31-03-2026    01-04-2014
1774                     31-03-2026    01-04-1996

[1775 rows x 13 columns]>

In [5]:
df.shape

(1775, 13)

In [6]:
df = pd.read_csv(
    "Projects_Report.csv",
    sep=r'\s{2,}',
    engine='python'
)

print(df.shape)
print(df.columns)
df.head()

(1781, 1)
Index(['Sr. No.,Sector Name,Line Ministry,Implementing Agency,Project Code,Project Name,"Original Cost'], dtype='object')

  Sr. No.,Sector Name,Line Ministry,Implementing Agency,Project Code,Project Name,"Original Cost
0                            (in cr.)","Revised Cost
1                             (in cr.)","Expenditure
2                       (in cr.)","Physical Progress
3                                  (in %)","Original
4                    Date of Commissioning","Revised

In [7]:
import pandas as pd

df = pd.read_csv("Projects_Report.csv")
df.columns = (
    df.columns
    .str.replace('\n', ' ', regex=False)
    .str.replace(r'\\n', ' ', regex=True)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

print("Shape:", df.shape)
print("Columns:")
print(df.columns.tolist())

df.head()

Shape: (1775, 13)
Columns:
['Sr. No.', 'Sector Name', 'Line Ministry', 'Implementing Agency', 'Project Code', 'Project Name', 'Original Cost (in cr.)', 'Revised Cost (in cr.)', 'Expenditure (in cr.)', 'Physical Progress (in %)', 'Original Date of Commissioning', 'Revised Date of Commissioning', 'Sanction Date']

,Sr. No.,Sector Name,Line Ministry,Implementing Agency,Project Code,Project Name,Original Cost (in cr.),Revised Cost (in cr.),Expenditure (in cr.),Physical Progress (in %),Original Date of Commissioning,Revised Date of Commissioning,Sanction Date
0,1,Aviation & Aviation Infrastructure,Ministry of Civil Aviation,Airport Authority of India [AAI],706718,C/o NITB Imphal Airport,499,499.0,212.17,53,13-07-2024,31-12-2026,01-11-2021
1,2,Aviation & Aviation Infrastructure,Ministry of Civil Aviation,Airport Authority of India [AAI],701121,Construction of New Domestic Terminal Building...,347,0.0,189.48,96,13-08-2025,25-08-2026,30-12-2022
2,3,Aviation & Aviation Infrastructure,Ministry of Civil Aviation,Airport Authority of India [AAI],701101,Construction of New Domestic Terminal Building...,1217,1216.9,1203.48,99,31-05-2026,31-08-2026,04-10-2018
3,4,Aviation & Aviation Infrastructure,Ministry of Civil Aviation,Airport Authority of India [AAI],612788,Construction of New Domestic Terminal Building...,322,0.0,240.99,97,01-02-2026,31-08-2026,02-06-2023
4,5,Aviation & Aviation Infrastructure,Ministry of Civil Aviation,Airport Authority of India [AAI],612787,Construction of New Domestic Terminal Building...,320,0.0,169.11,88,21-01-2026,30-09-2026,02-06-2023

In [8]:
df.head(1)

,Sr. No.,Sector Name,Line Ministry,Implementing Agency,Project Code,Project Name,Original Cost (in cr.),Revised Cost (in cr.),Expenditure (in cr.),Physical Progress (in %),Original Date of Commissioning,Revised Date of Commissioning,Sanction Date
0,1,Aviation & Aviation Infrastructure,Ministry of Civil Aviation,Airport Authority of India [AAI],706718,C/o NITB Imphal Airport,499,499.0,212.17,53,13-07-2024,31-12-2026,01-11-2021

In [9]:
df.head(1)["Project Code"].values

array([706718])

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1775 entries, 0 to 1774
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Sr. No.                         1775 non-null   int64
 1   Sector Name                     1775 non-null   object
 2   Line Ministry                   1775 non-null   object
 3   Implementing Agency             1775 non-null   object
 4   Project Code                    1775 non-null   int64
 5   Project Name                    1775 non-null   object
 6   Original Cost (in cr.)          1775 non-null   int64
 7   Revised Cost (in cr.)           1775 non-null   float64
 8   Expenditure (in cr.)            1775 non-null   float64
 9   Physical Progress (in %)        1775 non-null   int64
 10  Original Date of Commissioning  1775 non-null   object
 11  Revised Date of Commissioning   1427 non-null   object
 12  Sanction Date                   1763 non-null   object
dtypes: float64(2), int64(4), object(7)
memory usage: 180.4+ KB

In [11]:
date_cols = [
    'Original Date of Commissioning',
    'Revised Date of Commissioning',
    'Sanction Date'
]

for col in date_cols:
    df[col] = pd.to_datetime(df[col], dayfirst=True, errors='coerce')

In [12]:
df[date_cols].dtypes

Original Date of Commissioning    datetime64[ns]
Revised Date of Commissioning     datetime64[ns]
Sanction Date                     datetime64[ns]
dtype: object

In [13]:
# 1. Cost overrun percentage
df['Cost Overrun (%)'] = (
    (df['Revised Cost (in cr.)'] - df['Original Cost (in cr.)'])
    / df['Original Cost (in cr.)']
) * 100

# 2. Delay in days
df['Delay Days'] = (
    df['Revised Date of Commissioning']
    - df['Original Date of Commissioning']
).dt.days

# 3. Cost overrun flag
df['Cost Overrun Flag'] = (
    df['Cost Overrun (%)'] > 0
).astype(int)

# 4. Delay flag
df['Delay Flag'] = (
    df['Delay Days'] > 0
).astype(int)

In [14]:
df[
    [
        'Project Name',
        'Original Cost (in cr.)',
        'Revised Cost (in cr.)',
        'Cost Overrun (%)',
        'Delay Days',
        'Cost Overrun Flag',
        'Delay Flag'
    ]
].head(10)

,Project Name,Original Cost (in cr.),Revised Cost (in cr.),Cost Overrun (%),Delay Days,Cost Overrun Flag,Delay Flag
0,C/o NITB Imphal Airport,499,499.00,0.000000,901.0,0,1
1,Construction of New Domestic Terminal Building...,347,0.00,-100.000000,377.0,0,1
2,Construction of New Domestic Terminal Building...,1217,1216.90,-0.008217,92.0,0,1
3,Construction of New Domestic Terminal Building...,322,0.00,-100.000000,211.0,0,1
4,Construction of New Domestic Terminal Building...,320,0.00,-100.000000,252.0,0,1
5,Construction of New Domestic Terminal Building...,266,0.00,-100.000000,246.0,0,1
6,Construction of New Integrated Passenger Termi...,887,887.00,0.000000,200.0,0,1
7,Construction of New Integrated Terminal Buildi...,612,824.28,34.686275,1528.0,1,1
8,Construction of New Passenger Terminal Buildin...,480,480.00,0.000000,76.0,0,1
9,"Construction of NTB complex including apron, t...",861,861.37,0.042973,162.0,1,1

In [15]:
print("Missing revised dates:",
      df['Revised Date of Commissioning'].isna().sum())

print("Projects with cost overrun:",
      df['Cost Overrun Flag'].sum())

print("Projects with delay:",
      df['Delay Flag'].sum())

Missing revised dates: 348
Projects with cost overrun: 535
Projects with delay: 1129

In [16]:
# Reset delay flag for projects where revised date is missing
df.loc[
    df['Revised Date of Commissioning'].isna(),
    'Delay Flag'
] = pd.NA

In [17]:
print(df['Delay Flag'].value_counts(dropna=False))

Delay Flag
1.0    1129
NaN     348
0.0     298
Name: count, dtype: int64

In [18]:
# Project duration in days
df['Planned Duration (days)'] = (
    df['Original Date of Commissioning']
    - df['Sanction Date']
).dt.days

# Years between sanction and planned completion
df['Planned Duration (years)'] = (
    df['Planned Duration (days)'] / 365.25
)

# Expenditure as percentage of original cost
df['Expenditure Ratio (%)'] = (
    df['Expenditure (in cr.)']
    / df['Original Cost (in cr.)']
) * 100

# Difference between expenditure and physical progress
df['Progress Gap (%)'] = (
    df['Expenditure Ratio (%)']
    - df['Physical Progress (in %)']
)

In [19]:
df[
    [
        'Project Name',
        'Planned Duration (days)',
        'Planned Duration (years)',
        'Expenditure Ratio (%)',
        'Progress Gap (%)',
        'Cost Overrun Flag',
        'Delay Flag'
    ]
].head(10)

,Project Name,Planned Duration (days),Planned Duration (years),Expenditure Ratio (%),Progress Gap (%),Cost Overrun Flag,Delay Flag
0,C/o NITB Imphal Airport,985.0,2.696783,42.519038,-10.480962,0,1.0
1,Construction of New Domestic Terminal Building...,957.0,2.620123,54.605187,-41.394813,0,1.0
2,Construction of New Domestic Terminal Building...,2796.0,7.655031,98.889071,-0.110929,0,1.0
3,Construction of New Domestic Terminal Building...,975.0,2.669405,74.841615,-22.158385,0,1.0
4,Construction of New Domestic Terminal Building...,964.0,2.639288,52.846875,-35.153125,0,1.0
5,Construction of New Domestic Terminal Building...,1054.0,2.885695,66.308271,-13.691729,0,1.0
6,Construction of New Integrated Passenger Termi...,993.0,2.718686,66.202931,-12.797069,0,1.0
7,Construction of New Integrated Terminal Buildi...,809.0,2.214921,93.625817,3.625817,1,1.0
8,Construction of New Passenger Terminal Buildin...,1399.0,3.830253,72.541667,-27.458333,0,1.0
9,"Construction of NTB complex including apron, t...",985.0,2.696783,43.024390,-14.975610,1,1.0

In [20]:
print(df[
    [
        'Planned Duration (days)',
        'Planned Duration (years)',
        'Expenditure Ratio (%)',
        'Progress Gap (%)'
    ]
].describe())

       Planned Duration (days)  Planned Duration (years)  \
count              1763.000000               1763.000000
mean               1714.058990                  4.692838
std                2053.456172                  5.622057
min              -44390.000000               -121.533196
25%                1066.500000                  2.919918
50%                1346.000000                  3.685147
75%                1912.000000                  5.234771
max               15616.000000                 42.754278

       Expenditure Ratio (%)  Progress Gap (%)
count            1775.000000       1775.000000
mean               53.351054         -5.649509
std                64.702011         59.148845
min                 0.000000       -100.000000
25%                15.448835        -27.077969
50%                44.719409         -8.145124
75%                76.306370          3.899769
max              1197.675781       1132.675781

In [21]:
bad_duration = df[df['Planned Duration (days)'] < 0]

print("Negative duration projects:", len(bad_duration))

display(
    bad_duration[
        [
            'Project Name',
            'Sanction Date',
            'Original Date of Commissioning',
            'Planned Duration (days)'
        ]
    ].head(20)
)

Negative duration projects: 3

,Project Name,Sanction Date,Original Date of Commissioning,Planned Duration (days)
233,Establishment of new GMC Gondia,2021-07-15,1900-01-01,-44390.0
242,Establishment of new GMC Leh,2019-10-04,1900-01-01,-43740.0
1704,Jaipur Metro Phase 1D Project from Mansarovar ...,2026-05-13,2026-03-30,-44.0

In [22]:
df.loc[
    df['Planned Duration (days)'] < 0,
    'Planned Duration (days)'
] = pd.NA

df['Planned Duration (years)'] = (
    df['Planned Duration (days)'] / 365.25
)

In [23]:
print("Negative durations:",
      (df['Planned Duration (days)'] < 0).sum())

print("Missing durations:",
      df['Planned Duration (days)'].isna().sum())

Negative durations: 0
Missing durations: 15

In [24]:
high_exp = df[df['Expenditure Ratio (%)'] > 100]

print("Expenditure ratio > 100%:", len(high_exp))

display(
    high_exp[
        [
            'Project Name',
            'Original Cost (in cr.)',
            'Revised Cost (in cr.)',
            'Expenditure (in cr.)',
            'Expenditure Ratio (%)',
            'Physical Progress (in %)'
        ]
    ].sort_values(
        'Expenditure Ratio (%)',
        ascending=False
    ).head(20)
)

Expenditure ratio > 100%: 183

,Project Name,Original Cost (in cr.),Revised Cost (in cr.),Expenditure (in cr.),Expenditure Ratio (%),Physical Progress (in %)
1760,Lower Pedhi Project,256,1480.70,3066.05,1197.675781,65
415,"Dahod-Indore via Sardarpur, Jhabua & Dhar 200....",456,9217.23,4509.30,988.881579,57
1745,Aruna Medium Irrigation Project,210,1472.14,1734.71,826.052381,100
393,Baramati - Lonand 54 km,138,1790.50,1132.25,820.471014,60
1753,Integrated Anandpur Barrage Project,567,2990.05,2810.10,495.608466,63
1761,Madhya Ganga canal Phase-II,1061,4417.21,4575.74,431.266730,82
205,Subansiri Lower HE Project [2000 MW],6285,26075.50,26448.10,420.813047,98
1762,Nardave Medium Irrigation Project,211,781.85,879.80,416.966825,75
1752,Indiramma Flood Flow Canal Project,1331,5940.09,4491.08,337.421488,92
264,CONSTRUCTION OF 300 BEDDED HOSPITAL AT HARIDWAR,102,297.63,340.30,333.627451,90
519,Ratlam-Mhow-Khandwa-Akola 472.64 km including ...,1656,13314.50,5045.54,304.682367,75
248,Establishment of new GMC Porbandar,325,618.98,936.64,288.196923,81
1756,Kanupur Irrigation Project,989,2301.28,2804.16,283.534884,80
1101,Construction of twin tube tunnels on Jammu Kas...,243,731.59,677.47,278.794239,84
1764,Polavaram Irrigation Project,10151,55548.90,27961.50,275.455620,86
1771,"Subernarekha Project, Odisha",3056,7023.19,8327.62,272.500654,96
232,Establishment of new GMC Gangtok,250,635.21,667.21,266.884000,92
208,Tapovan-Vishnugad HEP [4x130 MW],2978,10907.30,7827.81,262.854600,76
1766,Sardar Gouthu Latchanna Thotapalli Barrage Pro...,353,1023.24,879.15,249.050992,96
557,Western Dedicated Freight Corridor,51101,124005.00,124623.00,243.875854,96

In [25]:
print("Original Cost <= 0:",
      (df['Original Cost (in cr.)'] <= 0).sum())

print("Revised Cost <= 0:",
      (df['Revised Cost (in cr.)'] <= 0).sum())

print("Physical Progress > 100:",
      (df['Physical Progress (in %)'] > 100).sum())

Original Cost <= 0: 0
Revised Cost <= 0: 833
Physical Progress > 100: 0

In [26]:
print(
    df[df['Revised Cost (in cr.)'] <= 0][
        [
            'Project Name',
            'Original Cost (in cr.)',
            'Revised Cost (in cr.)',
            'Expenditure (in cr.)',
            'Physical Progress (in %)',
            'Original Date of Commissioning',
            'Revised Date of Commissioning'
        ]
    ].head(20)
)

                                         Project Name  Original Cost (in cr.)  \
1   Construction of New Domestic Terminal Building...                     347
3   Construction of New Domestic Terminal Building...                     322
4   Construction of New Domestic Terminal Building...                     320
5   Construction of New Domestic Terminal Building...                     266
11  Development of additional RESA on either end o...                     485
13                     Development of Keshod Airport.                     363
14  Development of Lal Bahadur Shastri Internation...                    2870
15  Development of New Civil Enclave and associate...                     912
17          Development of New Civil Enclave at Bihta                    1413
18  Development of New Greenfield Airport at Bundi...                    1507
19  Development of New Integrated Civil Enclave at...                     579
21  Modernization of Chennai Airport, Phase II, Pa...                    1207
22  Re-Construction of Rigid portions of Secondary...                     328
23  SITC of ATM Automation System and ASMGCS [Incl...                     500
24  Widening of basic strip at Western Side of Run...                     323
25                        JAGANNATHPUR OC RCE PROJECT                     459
26                          Pachwara South Coal Block                    2243
27                                ADASA UG TO OC MINE                     316
28                                AMADAND OCP[4.0MTY]                     869
29                     AMAL GONDEGAON GHATROHANA EXPN                     669

    Revised Cost (in cr.)  Expenditure (in cr.)  Physical Progress (in %)  \
1                     0.0                189.48                        96
3                     0.0                240.99                        97
4                     0.0                169.11                        88
5                     0.0                176.38                        80
11                    0.0                242.51                        66
13                    0.0                108.64                        47
14                    0.0                746.93                        33
15                    0.0                426.22                        71
17                    0.0                 15.53                         4
18                    0.0                 81.41                        14
19                    0.0                224.58                        45
21                    0.0                331.85                        46
22                    0.0                153.52                        74
23                    0.0                399.77                        80
24                    0.0                 87.61                        36
25                    0.0                290.40                        96
26                    0.0               1432.45                        87
27                    0.0                209.29                        86
28                    0.0                325.09                        75
29                    0.0                  2.95                         3

   Original Date of Commissioning Revised Date of Commissioning
1                      2025-08-13                    2026-08-25
3                      2026-02-01                    2026-08-31
4                      2026-01-21                    2026-09-30
5                      2026-01-27                    2026-09-30
11                     2025-09-28                    2026-12-31
13                     2027-01-31                           NaT
14                     2027-07-20                    2027-07-20
15                     2026-07-11                    2026-11-30
17                     2027-03-31                           NaT
18                     2027-10-19                    2027-11-13
19                     2026-07-04                    2026-11-30
21                     2025-07-31                    2026-12-31
22                     2025-10-02                    2026-08-31
23                     2025-09-11                    2026-08-31
24                     2026-06-02                    2027-06-30
25                     2025-03-31                    2027-03-31
26                     2028-09-30                           NaT
27                     2024-03-31                    2027-03-31
28                     2021-03-31                    2027-03-31
29                     2029-03-31                           NaT

In [27]:
df['Cost Base (in cr.)'] = df['Revised Cost (in cr.)']

df.loc[
    df['Cost Base (in cr.)'] <= 0,
    'Cost Base (in cr.)'
] = df['Original Cost (in cr.)']

In [28]:
df['Expenditure Ratio (%)'] = (
    df['Expenditure (in cr.)']
    / df['Cost Base (in cr.)']
) * 100

In [29]:
df['Expenditure-Progress Gap (%)'] = (
    df['Expenditure Ratio (%)']
    - df['Physical Progress (in %)']
)

In [30]:
df[
    [
        'Expenditure Ratio (%)',
        'Expenditure-Progress Gap (%)'
    ]
].describe()

       Expenditure Ratio (%)  Expenditure-Progress Gap (%)
count            1775.000000                   1775.000000
mean               69.577578                     10.577014
std               998.279382                    998.942169
min                 0.000000                   -100.000000
25%                16.291643                    -27.243504
50%                45.008753                     -9.079556
75%                71.329277                      0.633242
max             42080.000000                  42057.000000

In [31]:
print(
    "Expenditure ratio > 100%:",
    (df['Expenditure Ratio (%)'] > 100).sum()
)

print(
    "Expenditure ratio > 200%:",
    (df['Expenditure Ratio (%)'] > 200).sum()
)

Expenditure ratio > 100%: 59
Expenditure ratio > 200%: 3

In [32]:
extreme_exp = df[df['Expenditure Ratio (%)'] > 200]

display(
    extreme_exp[
        [
            'Project Name',
            'Original Cost (in cr.)',
            'Revised Cost (in cr.)',
            'Cost Base (in cr.)',
            'Expenditure (in cr.)',
            'Expenditure Ratio (%)',
            'Physical Progress (in %)',
            'Expenditure-Progress Gap (%)'
        ]
    ].sort_values(
        'Expenditure Ratio (%)',
        ascending=False
    )
)

,Project Name,Original Cost (in cr.),Revised Cost (in cr.),Cost Base (in cr.),Expenditure (in cr.),Expenditure Ratio (%),Physical Progress (in %),Expenditure-Progress Gap (%)
1359,Road Safety Improvement of Critical Junctions ...,239,0.1,0.1,42.08,42080.000000,23,42057.000000
1617,BharatNet,61109,12709.0,12709.0,48809.70,384.056181,100,284.056181
1760,Lower Pedhi Project,256,1480.7,1480.7,3066.05,207.067603,65,142.067603

In [33]:
df['Cost Base Anomaly'] = (
    (df['Revised Cost (in cr.)'] > 0) &
    (df['Expenditure (in cr.)'] > 10 * df['Revised Cost (in cr.)'])
).astype(int)

In [34]:
df[df['Cost Base Anomaly'] == 1][
    [
        'Project Name',
        'Original Cost (in cr.)',
        'Revised Cost (in cr.)',
        'Expenditure (in cr.)',
        'Expenditure Ratio (%)'
    ]
]

,Project Name,Original Cost (in cr.),Revised Cost (in cr.),Expenditure (in cr.),Expenditure Ratio (%)
1359,Road Safety Improvement of Critical Junctions ...,239,0.1,42.08,42080.0

In [35]:
print(df['Cost Base Anomaly'].value_counts())

Cost Base Anomaly
0    1774
1       1
Name: count, dtype: int64

In [36]:
model_df = df[
    [
        'Sector Name',
        'Line Ministry',
        'Implementing Agency',
        'Original Cost (in cr.)',
        'Expenditure (in cr.)',
        'Physical Progress (in %)',
        'Planned Duration (days)',
        'Expenditure Ratio (%)',
        'Expenditure-Progress Gap (%)',
        'Cost Base Anomaly',
        'Cost Overrun Flag',
        'Delay Flag'
    ]
].copy()

In [37]:
print(model_df['Delay Flag'].value_counts(dropna=False))

Delay Flag
1.0    1129
NaN     348
0.0     298
Name: count, dtype: int64

In [38]:
delay_df = model_df.dropna(
    subset=['Delay Flag']
).copy()

print("Total projects:", len(model_df))
print("Projects available for delay model:", len(delay_df))

Total projects: 1775
Projects available for delay model: 1427

In [39]:
print(model_df['Cost Overrun Flag'].value_counts(dropna=False))

Cost Overrun Flag
0    1240
1     535
Name: count, dtype: int64

In [40]:
# Features for Cost Overrun prediction
features = [
    'Sector Name',
    'Line Ministry',
    'Implementing Agency',
    'Original Cost (in cr.)',
    'Expenditure (in cr.)',
    'Physical Progress (in %)',
    'Planned Duration (days)',
    'Expenditure Ratio (%)',
    'Expenditure-Progress Gap (%)',
    'Cost Base Anomaly'
]

X = df[features].copy()
y = df['Cost Overrun Flag'].copy()

print("X shape:", X.shape)
print("y shape:", y.shape)
print("\nTarget distribution:")
print(y.value_counts())

X shape: (1775, 10)
y shape: (1775,)

Target distribution:
Cost Overrun Flag
0    1240
1     535
Name: count, dtype: int64

In [41]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_auc_score
)


# Separate categorical/numerical features
# -----------------------------

categorical_features = [
    'Sector Name',
    'Line Ministry',
    'Implementing Agency'
]

numerical_features = [
    'Original Cost (in cr.)',
    'Expenditure (in cr.)',
    'Physical Progress (in %)',
    'Planned Duration (days)',
    'Expenditure Ratio (%)',
    'Expenditure-Progress Gap (%)',
    'Cost Base Anomaly'
]

# -----------------------------
# Preprocessing
# -----------------------------

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median'))
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(
        handle_unknown='ignore',
        sparse_output=False
    ))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ]
)

# -----------------------------
# Train/Test Split
# -----------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (1420, 10)
Testing data: (355, 10)

In [42]:
# ==============================
# STEP 4: COST OVERRUN MODEL
# ==============================

# Create pipeline
cost_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(
        n_estimators=300,
        random_state=42,
        class_weight='balanced',
        max_depth=12,
        min_samples_split=5,
        n_jobs=-1
    ))
])

# Train model
cost_model.fit(X_train, y_train)

print("Cost Overrun Model trained successfull")

Cost Overrun Model trained successfull

In [43]:
# ==============================
# MODEL EVALUATION
# ==============================

y_pred = cost_model.predict(X_test)
y_prob = cost_model.predict_proba(X_test)[:, 1]

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nROC-AUC Score:")
print(roc_auc_score(y_test, y_prob))

Accuracy: 0.8

Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.85      0.86       248
           1       0.67      0.67      0.67       107

    accuracy                           0.80       355
   macro avg       0.76      0.76      0.76       355
weighted avg       0.80      0.80      0.80       355


Confusion Matrix:
[[212  36]
 [ 35  72]]

ROC-AUC Score:
0.8824992463069038

In [44]:
# ==========================================
# STEP 5: FEATURE IMPORTANCE
# ==========================================

# Get trained Random Forest
rf_model = cost_model.named_steps['classifier']

# Get transformed feature names
feature_names = cost_model.named_steps[
    'preprocessor'
].get_feature_names_out()

# Get importance
importances = rf_model.feature_importances_

# Create dataframe
importance_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': importances
})

# Sort
importance_df = importance_df.sort_values(
    by='Importance',
    ascending=False
)

print(importance_df.head(20))

                                               Feature  Importance
1                            num__Expenditure (in cr.)    0.186819
4                           num__Expenditure Ratio (%)    0.119822
2                        num__Physical Progress (in %)    0.118537
3                         num__Planned Duration (days)    0.094854
0                          num__Original Cost (in cr.)    0.085849
5                    num__Expenditure-Progress Gap (%)    0.069970
149                      cat__Implementing Agency_NHAI    0.027967
145                     cat__Implementing Agency_MoRTH    0.024235
150                    cat__Implementing Agency_NHIDCL    0.022362
8                                cat__Sector Name_Coal    0.020849
35                 cat__Line Ministry_Ministry of Coal    0.020312
43             cat__Line Ministry_Ministry of Railways    0.017421
18                           cat__Sector Name_Railways    0.015560
25        cat__Sector Name_Transmission & Distribution    0.008050
40   cat__Line Ministry_Ministry of Petroleum & Nat...    0.007388
44   cat__Line Ministry_Ministry of Road Transport ...    0.007316
183  cat__Implementing Agency_Power Grid Corporatio...    0.006620
28                    cat__Sector Name_Water Resources    0.006616
20                   cat__Sector Name_Roads & Highways    0.006284
17                          cat__Sector Name_Oil & Gas    0.006058

In [45]:
print("Delay Flag distribution:")
print(df['Delay Flag'].value_counts(dropna=False))

print("\nMissing Delay Flags:")
print(df['Delay Flag'].isna().sum())

Delay Flag distribution:
Delay Flag
1.0    1129
NaN     348
0.0     298
Name: count, dtype: int64

Missing Delay Flags:
348

In [46]:
# ==========================================
# STEP 6: PREPARE DELAY MODEL
# ==========================================

delay_features = [
    'Sector Name',
    'Line Ministry',
    'Implementing Agency',
    'Original Cost (in cr.)',
    'Expenditure (in cr.)',
    'Physical Progress (in %)',
    'Planned Duration (days)',
    'Expenditure Ratio (%)',
    'Expenditure-Progress Gap (%)',
    'Cost Base Anomaly'
]

# Keep only projects with known delay outcome
delay_df = df.dropna(subset=['Delay Flag']).copy()

X_delay = delay_df[delay_features].copy()
y_delay = delay_df['Delay Flag'].astype(int)

print("Delay dataset shape:", X_delay.shape)

print("\nDelay target distribution:")
print(y_delay.value_counts())

print("\nDelay target percentage:")
print(y_delay.value_counts(normalize=True) * 100)

Delay dataset shape: (1427, 10)

Delay target distribution:
Delay Flag
1    1129
0     298
Name: count, dtype: int64

Delay target percentage:
Delay Flag
1    79.117029
0    20.882971
Name: proportion, dtype: float64

In [47]:
# ==========================================
# STEP 7: DELAY PREDICTION MODEL
# ==========================================

from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

# Split delay data
X_delay_train, X_delay_test, y_delay_train, y_delay_test = train_test_split(
    X_delay,
    y_delay,
    test_size=0.20,
    random_state=42,
    stratify=y_delay
)

print("Training data:", X_delay_train.shape)
print("Testing data:", X_delay_test.shape)


# Create Delay Model
delay_model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(
        n_estimators=300,
        random_state=42,
        class_weight='balanced',
        max_depth=12,
        min_samples_split=5,
        n_jobs=-1
    ))
])


# Train
delay_model.fit(X_delay_train, y_delay_train)

print("\nDelay Prediction Model trained successfully!")

Training data: (1141, 10)
Testing data: (286, 10)

Delay Prediction Model trained successfully!

In [48]:
# ==========================================
# STEP 8: DELAY MODEL EVALUATION
# ==========================================

y_delay_pred = delay_model.predict(X_delay_test)

y_delay_prob = delay_model.predict_proba(
    X_delay_test
)[:, 1]


print("Accuracy:",
      accuracy_score(y_delay_test, y_delay_pred))

print("\nClassification Report:")
print(
    classification_report(
        y_delay_test,
        y_delay_pred
    )
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_delay_test,
        y_delay_pred
    )
)

print("\nROC-AUC Score:")
print(
    roc_auc_score(
        y_delay_test,
        y_delay_prob
    )
)

Accuracy: 0.8846153846153846

Classification Report:
              precision    recall  f1-score   support

           0       0.70      0.80      0.74        60
           1       0.94      0.91      0.93       226

    accuracy                           0.88       286
   macro avg       0.82      0.85      0.83       286
weighted avg       0.89      0.88      0.89       286


Confusion Matrix:
[[ 48  12]
 [ 21 205]]

ROC-AUC Score:
0.9250737463126845

In [49]:
# ==========================================
# STEP 9: OVERALL PROJECT RISK SCORE
# ==========================================

def calculate_risk_score(cost_probability, delay_probability):

    # Convert probabilities to percentages
    cost_risk = cost_probability * 100
    delay_risk = delay_probability * 100

    # Equal weighting
    overall_score = (
        0.50 * cost_risk +
        0.50 * delay_risk
    )

    # Risk category
    if overall_score < 30:
        risk_level = "LOW"
    elif overall_score < 60:
        risk_level = "MEDIUM"
    else:
        risk_level = "HIGH"

    return round(overall_score, 2), risk_level

In [50]:
# Example
cost_probability = 0.82
delay_probability = 0.74

score, level = calculate_risk_score(
    cost_probability,
    delay_probability
)

print("Cost Risk:", cost_probability * 100, "%")
print("Delay Risk:", delay_probability * 100, "%")
print("Overall Risk Score:", score)
print("Risk Level:", level)

Cost Risk: 82.0 %
Delay Risk: 74.0 %
Overall Risk Score: 78.0
Risk Level: HIGH

In [51]:
# ==========================================
# EARLY WARNING SYSTEM
# ==========================================

def generate_warning(cost_probability, delay_probability):

    score, level = calculate_risk_score(
        cost_probability,
        delay_probability
    )

    if level == "HIGH":
        warning = "IMMEDIATE ATTENTION REQUIRED"

    elif level == "MEDIUM":
        warning = "CLOSE MONITORING REQUIRED"

    else:
        warning = "PROJECT APPEARS STABLE"

    return score, level, warning

In [52]:
score, level, warning = generate_warning(
    0.82,
    0.74
)

print("Overall Risk:", score)
print("Risk Level:", level)
print("Early Warning:", warning)

Overall Risk: 78.0
Risk Level: HIGH
Early Warning: IMMEDIATE ATTENTION REQUIRED

In [53]:
# ==========================================
# STEP 10: TOP COST ESCALATION DRIVERS
# ==========================================

cost_importance = importance_df.copy()

# Remove preprocessing prefixes
cost_importance['Feature'] = (
    cost_importance['Feature']
    .str.replace('num__', '', regex=False)
    .str.replace('cat__', '', regex=False)
)

# Top 10
top_drivers = cost_importance.head(10).copy()

print("Top 10 Cost Escalation Drivers:")
print(top_drivers.to_string(index=False))

Top 10 Cost Escalation Drivers:
                     Feature  Importance
        Expenditure (in cr.)    0.186819
       Expenditure Ratio (%)    0.119822
    Physical Progress (in %)    0.118537
     Planned Duration (days)    0.094854
      Original Cost (in cr.)    0.085849
Expenditure-Progress Gap (%)    0.069970
    Implementing Agency_NHAI    0.027967
   Implementing Agency_MoRTH    0.024235
  Implementing Agency_NHIDCL    0.022362
            Sector Name_Coal    0.020849

In [54]:
!pip install shap

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: shap in c:\users\dell\appdata\roaming\python\python313\site-packages (0.52.0)
Requirement already satisfied: numpy>=2 in c:\programdata\anaconda3\lib\site-packages (from shap) (2.3.5)
Requirement already satisfied: scipy in c:\programdata\anaconda3\lib\site-packages (from shap) (1.16.3)
Requirement already satisfied: scikit-learn in c:\programdata\anaconda3\lib\site-packages (from shap) (1.7.2)
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (from shap) (2.3.3)
Requirement already satisfied: tqdm>=4.27.0 in c:\programdata\anaconda3\lib\site-packages (from shap) (4.67.1)
Requirement already satisfied: packaging>20.9 in c:\programdata\anaconda3\lib\site-packages (from shap) (25.0)
Requirement already satisfied: slicer==0.0.8 in c:\users\dell\appdata\roaming\python\python313\site-packages (from shap) (0.0.8)
Requirement already satisfied: numba in c:\programdata\anaconda3\lib\site-packages (from shap) (0.62.1)
Requirement already satisfied: llvmlite in c:\programdata\anaconda3\lib\site-packages (from shap) (0.45.1)
Requirement already satisfied: cloudpickle in c:\programdata\anaconda3\lib\site-packages (from shap) (3.1.1)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm>=4.27.0->shap) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas->shap) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas->shap) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas->shap) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->shap) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn->shap) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn->shap) (3.5.0)

In [55]:
import shap

print("SHAP version:", shap.__version__)

SHAP version: 0.52.0

In [56]:
# import shap

# # Transform test data
# X_test_transformed = cost_model.named_steps[
#     'preprocessor'
# ].transform(X_test)

# # Get trained Random Forest
# rf_model = cost_model.named_steps[
#     'classifier'
# ]


# # Create SHAP explainer
# explainer = shap.TreeExplainer(rf_model)

# # # Calculate SHAP values
# # shap_values = explainer.shap_values(
# #     X_test_transformed
# # )

# print("SHAP values calculated successfully!")

In [57]:
df
X
y
preprocessor
X_train
X_test
cost_model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['Original Cost (in cr.)',
                                                   'Expenditure (in cr.)',
                                                   'Physical Progress (in %)',
                                                   'Planned Duration (days)',
                                                   'Expenditure Ratio (%)',
                                                   'Expenditure-Progress Gap '
                                                   '(%)',
                                                   'Cost Base Anomaly']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Sector Name',
                                                   'Line Ministry',
                                                   'Implementing Agency'])])),
                ('classifier',
                 RandomForestClassifier(class_weight='balanced', max_depth=12,
                                        min_samples_split=5, n_estimators=300,
                                        n_jobs=-1, random_state=42))])

In [58]:
import joblib

joblib.dump(cost_model, "cost_model.pkl")
print("Cost model saved!")

Cost model saved!

In [59]:
joblib.dump(delay_model, "delay_model.pkl")
print("Delay model saved!")

Delay model saved!

In [60]:
import joblib

# Load saved models
cost_model = joblib.load("cost_model.pkl")
delay_model = joblib.load("delay_model.pkl")

print("Cost model loaded:", type(cost_model))
print("Delay model loaded:", type(delay_model))

Cost model loaded: <class 'sklearn.pipeline.Pipeline'>
Delay model loaded: <class 'sklearn.pipeline.Pipeline'>

In [61]:
# ==========================================
# STEP 11: COMPLETE PROJECT RISK PREDICTION
# ==========================================

import pandas as pd
import numpy as np
import joblib

# Load saved models
cost_model = joblib.load("cost_model.pkl")
delay_model = joblib.load("delay_model.pkl")


def predict_project_risk(project):

    # -------------------------------
    # 1. Create input dataframe
    # -------------------------------
    input_data = pd.DataFrame([project])

    # -------------------------------
    # 2. Cost Overrun Prediction
    # -------------------------------
    cost_probability = cost_model.predict_proba(
        input_data
    )[0][1]

    cost_prediction = cost_model.predict(
        input_data
    )[0]

    # -------------------------------
    # 3. Delay Prediction
    # -------------------------------
    delay_probability = delay_model.predict_proba(
        input_data
    )[0][1]

    delay_prediction = delay_model.predict(
        input_data
    )[0]

    # -------------------------------
    # 4. Convert to percentage
    # -------------------------------
    cost_risk = cost_probability * 100
    delay_risk = delay_probability * 100

    # -------------------------------
    # 5. Overall Risk Score
    # -------------------------------
    overall_score = (
        0.50 * cost_risk +
        0.50 * delay_risk
    )

    # -------------------------------
    # 6. Risk Level
    # -------------------------------
    if overall_score < 30:
        risk_level = "LOW"
        warning = "PROJECT APPEARS STABLE"

    elif overall_score < 60:
        risk_level = "MEDIUM"
        warning = "CLOSE MONITORING REQUIRED"

    else:
        risk_level = "HIGH"
        warning = "IMMEDIATE ATTENTION REQUIRED"

    # -------------------------------
    # 7. Risk Factors
    # -------------------------------
    risk_factors = []

    if project["Expenditure Ratio (%)"] > 100:
        risk_factors.append(
            "Expenditure has exceeded the project cost base"
        )

    if project["Expenditure-Progress Gap (%)"] > 20:
        risk_factors.append(
            "High expenditure-progress gap"
        )

    if project["Physical Progress (in %)"] < 50:
        risk_factors.append(
            "Low physical progress"
        )

    if project["Planned Duration (days)"] > 2000:
        risk_factors.append(
            "Long planned project duration"
        )

    if project["Revised Cost (in cr.)"] > project["Original Cost (in cr.)"]:
        risk_factors.append(
            "Revised cost is higher than original cost"
        )

    if not risk_factors:
        risk_factors.append(
            "No major threshold-based risk factor detected"
        )

    # -------------------------------
    # 8. Return results
    # -------------------------------
    return {
        "Cost Overrun Probability": round(cost_risk, 2),
        "Cost Overrun Prediction": (
            "YES" if cost_prediction == 1 else "NO"
        ),

        "Delay Probability": round(delay_risk, 2),
        "Delay Prediction": (
            "YES" if delay_prediction == 1 else "NO"
        ),

        "Overall Risk Score": round(overall_score, 2),
        "Risk Level": risk_level,
        "Early Warning": warning,
        "Risk Factors": risk_factors
    }

print("Prediction function created successfully!")

Prediction function created successfully!

In [62]:
print(df.columns.tolist())

['Sr. No.', 'Sector Name', 'Line Ministry', 'Implementing Agency', 'Project Code', 'Project Name', 'Original Cost (in cr.)', 'Revised Cost (in cr.)', 'Expenditure (in cr.)', 'Physical Progress (in %)', 'Original Date of Commissioning', 'Revised Date of Commissioning', 'Sanction Date', 'Cost Overrun (%)', 'Delay Days', 'Cost Overrun Flag', 'Delay Flag', 'Planned Duration (days)', 'Planned Duration (years)', 'Expenditure Ratio (%)', 'Progress Gap (%)', 'Cost Base (in cr.)', 'Expenditure-Progress Gap (%)', 'Cost Base Anomaly']

In [63]:
print("Cost model expects:")
print(cost_model.named_steps['preprocessor'].feature_names_in_)

print("\nDelay model expects:")
print(delay_model.named_steps['preprocessor'].feature_names_in_)

Cost model expects:
['Sector Name' 'Line Ministry' 'Implementing Agency'
 'Original Cost (in cr.)' 'Expenditure (in cr.)'
 'Physical Progress (in %)' 'Planned Duration (days)'
 'Expenditure Ratio (%)' 'Expenditure-Progress Gap (%)'
 'Cost Base Anomaly']

Delay model expects:
['Sector Name' 'Line Ministry' 'Implementing Agency'
 'Original Cost (in cr.)' 'Expenditure (in cr.)'
 'Physical Progress (in %)' 'Planned Duration (days)'
 'Expenditure Ratio (%)' 'Expenditure-Progress Gap (%)'
 'Cost Base Anomaly']

In [64]:
# ==========================================
# FIX: SEPARATE PREPROCESSORS
# ==========================================

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
import joblib

# ------------------------------------------
# Features
# ------------------------------------------

prediction_features = [
    'Sector Name',
    'Line Ministry',
    'Implementing Agency',
    'Original Cost (in cr.)',
    'Expenditure (in cr.)',
    'Physical Progress (in %)',
    'Planned Duration (days)',
    'Expenditure Ratio (%)',
    'Expenditure-Progress Gap (%)',
    'Cost Base Anomaly'
]

categorical_features = [
    'Sector Name',
    'Line Ministry',
    'Implementing Agency'
]

numeric_features = [
    'Original Cost (in cr.)',
    'Expenditure (in cr.)',
    'Physical Progress (in %)',
    'Planned Duration (days)',
    'Expenditure Ratio (%)',
    'Expenditure-Progress Gap (%)',
    'Cost Base Anomaly'
]

print("Features:", len(prediction_features))
print("Categorical:", len(categorical_features))
print("Numerical:", len(numeric_features))

Features: 10
Categorical: 3
Numerical: 7

In [65]:
# ==========================================
# COST MODEL PREPROCESSOR
# ==========================================

cost_preprocessor = ColumnTransformer(
    transformers=[
        (
            'num',
            Pipeline([
                ('imputer', SimpleImputer(strategy='median'))
            ]),
            numeric_features
        ),

        (
            'cat',
            Pipeline([
                ('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder', OneHotEncoder(
                    handle_unknown='ignore'
                ))
            ]),
            categorical_features
        )
    ]
)

print("Cost preprocessor created!")

Cost preprocessor created!

In [66]:
X_train
X_test
y_train
y_test

618     0
1136    1
558     0
1109    0
1011    0
       ..
1714    0
784     0
1724    0
1673    0
11      0
Name: Cost Overrun Flag, Length: 355, dtype: int64

In [67]:
# ==========================================
# RETRAIN COST MODEL
# ==========================================

cost_model = Pipeline([
    ('preprocessor', cost_preprocessor),

    ('classifier', RandomForestClassifier(
        n_estimators=300,
        random_state=42,
        class_weight='balanced',
        max_depth=12,
        min_samples_split=5,
        n_jobs=-1
    ))
])

cost_model.fit(X_train, y_train)

print("Cost model retrained successfully!")

Cost model retrained successfully!

In [68]:
# ==========================================
# CHECK COST MODEL
# ==========================================

X_cost_transformed = cost_model.named_steps[
    'preprocessor'
].transform(X_test)

rf_cost = cost_model.named_steps[
    'classifier'
]

print("Transformed features:",
      X_cost_transformed.shape[1])

print("Random Forest expects:",
      rf_cost.n_features_in_)

Transformed features: 212
Random Forest expects: 212

In [69]:
# ==========================================
# DELAY MODEL PREPROCESSOR
# ==========================================

delay_preprocessor = ColumnTransformer(
    transformers=[
        (
            'num',
            Pipeline([
                ('imputer', SimpleImputer(strategy='median'))
            ]),
            numeric_features
        ),

        (
            'cat',
            Pipeline([
                ('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder', OneHotEncoder(
                    handle_unknown='ignore'
                ))
            ]),
            categorical_features
        )
    ]
)

print("Delay preprocessor created!")

Delay preprocessor created!

In [70]:
X_delay
y_delay

0       1
1       1
2       1
3       1
4       1
       ..
1770    1
1771    1
1772    1
1773    1
1774    1
Name: Delay Flag, Length: 1427, dtype: int64

In [71]:
# ==========================================
# RETRAIN DELAY MODEL
# ==========================================

X_delay_train, X_delay_test, y_delay_train, y_delay_test = train_test_split(
    X_delay,
    y_delay,
    test_size=0.20,
    random_state=42,
    stratify=y_delay
)

delay_model = Pipeline([
    ('preprocessor', delay_preprocessor),

    ('classifier', RandomForestClassifier(
        n_estimators=300,
        random_state=42,
        class_weight='balanced',
        max_depth=12,
        min_samples_split=5,
        n_jobs=-1
    ))
])

delay_model.fit(
    X_delay_train,
    y_delay_train
)

print("Delay model retrained successfully!")

Delay model retrained successfully!

In [72]:
# ==========================================
# VERIFY BOTH MODELS
# ==========================================

# Cost
cost_transformed = cost_model.named_steps[
    'preprocessor'
].transform(X_test)

cost_rf = cost_model.named_steps[
    'classifier'
]

# Delay
delay_transformed = delay_model.named_steps[
    'preprocessor'
].transform(X_delay_test)

delay_rf = delay_model.named_steps[
    'classifier'
]

print("========== COST MODEL ==========")
print("Transformed features:", cost_transformed.shape[1])
print("RF expects:", cost_rf.n_features_in_)

print("\n========== DELAY MODEL ==========")
print("Transformed features:", delay_transformed.shape[1])
print("RF expects:", delay_rf.n_features_in_)

========== COST MODEL ==========
Transformed features: 212
RF expects: 212

========== DELAY MODEL ==========
Transformed features: 178
RF expects: 178

In [73]:
# ==========================================
# SAVE CORRECTED MODELS
# ==========================================

joblib.dump(cost_model, "cost_model.pkl")
joblib.dump(delay_model, "delay_model.pkl")

print("Both corrected models saved successfully!")

Both corrected models saved successfully!

In [74]:
# ==========================================
# FINAL PROJECT RISK PREDICTION FUNCTION
# ==========================================

def predict_project_risk(project):

    input_data = pd.DataFrame([project])

    # --------------------------------------
    # COST OVERRUN
    # --------------------------------------

    cost_probability = cost_model.predict_proba(
        input_data
    )[0][1]

    cost_prediction = cost_model.predict(
        input_data
    )[0]

    # --------------------------------------
    # DELAY
    # --------------------------------------

    delay_probability = delay_model.predict_proba(
        input_data
    )[0][1]

    delay_prediction = delay_model.predict(
        input_data
    )[0]

    # --------------------------------------
    # RISK %
    # --------------------------------------

    cost_risk = cost_probability * 100
    delay_risk = delay_probability * 100

    # --------------------------------------
    # OVERALL RISK
    # --------------------------------------

    overall_score = (
        0.50 * cost_risk +
        0.50 * delay_risk
    )

    # --------------------------------------
    # RISK LEVEL
    # --------------------------------------

    if overall_score < 30:

        risk_level = "LOW"
        warning = "PROJECT APPEARS STABLE"

    elif overall_score < 60:

        risk_level = "MEDIUM"
        warning = "CLOSE MONITORING REQUIRED"

    else:

        risk_level = "HIGH"
        warning = "IMMEDIATE ATTENTION REQUIRED"

    # --------------------------------------
    # RISK FACTORS
    # --------------------------------------

    risk_factors = []

    if project["Expenditure Ratio (%)"] > 100:
        risk_factors.append(
            "Expenditure has exceeded the cost base"
        )

    if project["Expenditure-Progress Gap (%)"] > 20:
        risk_factors.append(
            "High expenditure-progress gap"
        )

    if project["Physical Progress (in %)"] < 50:
        risk_factors.append(
            "Low physical progress"
        )

    if project["Planned Duration (days)"] > 2000:
        risk_factors.append(
            "Long planned project duration"
        )

    if project["Cost Base Anomaly"] == 1:
        risk_factors.append(
            "Abnormal cost base detected"
        )

    if not risk_factors:
        risk_factors.append(
            "No major threshold-based risk factor detected"
        )

    # --------------------------------------
    # RETURN
    # --------------------------------------

    return {

        "Cost Overrun Probability":
            round(cost_risk, 2),

        "Cost Overrun Prediction":
            "YES" if cost_prediction == 1 else "NO",

        "Delay Probability":
            round(delay_risk, 2),

        "Delay Prediction":
            "YES" if delay_prediction == 1 else "NO",

        "Overall Risk Score":
            round(overall_score, 2),

        "Risk Level":
            risk_level,

        "Early Warning":
            warning,

        "Risk Factors":
            risk_factors
    }

print("Final prediction function loaded successfully!")

Final prediction function loaded successfully!

In [75]:
# ==========================================
# TEST ONE REAL PROJECT
# ==========================================

project = df.iloc[0][prediction_features].to_dict()

result = predict_project_risk(project)

print("====================================")
print("       PROJECT RISK ANALYSIS")
print("====================================")

print("Cost Overrun Risk:",
      result["Cost Overrun Probability"], "%")

print("Cost Overrun Prediction:",
      result["Cost Overrun Prediction"])

print("Delay Risk:",
      result["Delay Probability"], "%")

print("Delay Prediction:",
      result["Delay Prediction"])

print("Overall Risk Score:",
      result["Overall Risk Score"], "/ 100")

print("Risk Level:",
      result["Risk Level"])

print("Early Warning:",
      result["Early Warning"])

print("\nRisk Factors:")

for factor in result["Risk Factors"]:
    print("-", factor)

====================================
       PROJECT RISK ANALYSIS
====================================
Cost Overrun Risk: 24.48 %
Cost Overrun Prediction: NO
Delay Risk: 82.1 %
Delay Prediction: YES
Overall Risk Score: 53.29 / 100
Risk Level: MEDIUM
Early Warning: CLOSE MONITORING REQUIRED

Risk Factors:
- No major threshold-based risk factor detected

In [76]:
import joblib

cost_model = joblib.load("cost_model.pkl")
delay_model = joblib.load("delay_model.pkl")

print("Cost model loaded successfully!")
print("Delay model loaded successfully!")

Cost model loaded successfully!
Delay model loaded successfully!

In [77]:
# ==========================================
# STEP 2: VERIFY SAVED MODEL FEATURES
# ==========================================

# Cost model
cost_preprocessor = cost_model.named_steps['preprocessor']
cost_rf = cost_model.named_steps['classifier']

# Delay model
delay_preprocessor = delay_model.named_steps['preprocessor']
delay_rf = delay_model.named_steps['classifier']

# Check transformed feature counts
cost_transformed = cost_preprocessor.transform(X_test)
delay_transformed = delay_preprocessor.transform(X_delay_test)

print("====================================")
print("       MODEL FEATURE CHECK")
print("====================================")

print("Cost Model:")
print("Preprocessor output:", cost_transformed.shape[1])
print("Random Forest expects:", cost_rf.n_features_in_)

print("\nDelay Model:")
print("Preprocessor output:", delay_transformed.shape[1])
print("Random Forest expects:", delay_rf.n_features_in_)

====================================
       MODEL FEATURE CHECK
====================================
Cost Model:
Preprocessor output: 212
Random Forest expects: 212

Delay Model:
Preprocessor output: 178
Random Forest expects: 178

In [78]:
# ==========================================
# STEP 3: SAFE SHAP TEST
# ==========================================

import shap

# Get the trained Random Forest models
cost_rf = cost_model.named_steps['classifier']
delay_rf = delay_model.named_steps['classifier']

# Transform ONLY ONE test sample
X_cost_one = cost_model.named_steps['preprocessor'].transform(
    X_test.iloc[[0]]
)

X_delay_one = delay_model.named_steps['preprocessor'].transform(
    X_delay_test.iloc[[0]]
)

print("Cost sample shape:", X_cost_one.shape)
print("Delay sample shape:", X_delay_one.shape)

# Create SHAP explainers
cost_explainer = shap.TreeExplainer(cost_rf)
delay_explainer = shap.TreeExplainer(delay_rf)

print("\nSHAP explainers created successfully!")

Cost sample shape: (1, 212)
Delay sample shape: (1, 178)

SHAP explainers created successfully!

In [79]:
# ==========================================
# STEP 4A: CONVERT SHAP INPUT TO NUMERIC
# ==========================================

import numpy as np

# Convert sparse matrix to dense if necessary
if hasattr(X_cost_one, "toarray"):
    X_cost_one_dense = X_cost_one.toarray()
else:
    X_cost_one_dense = np.asarray(X_cost_one)

if hasattr(X_delay_one, "toarray"):
    X_delay_one_dense = X_delay_one.toarray()
else:
    X_delay_one_dense = np.asarray(X_delay_one)

# Force numeric float type
X_cost_one_dense = np.asarray(X_cost_one_dense, dtype=np.float64)
X_delay_one_dense = np.asarray(X_delay_one_dense, dtype=np.float64)

print("Cost SHAP input:", X_cost_one_dense.shape)
print("Cost dtype:", X_cost_one_dense.dtype)

print("Delay SHAP input:", X_delay_one_dense.shape)
print("Delay dtype:", X_delay_one_dense.dtype)

Cost SHAP input: (1, 212)
Cost dtype: float64
Delay SHAP input: (1, 178)
Delay dtype: float64

In [80]:
# ==========================================
# STEP 4B: CALCULATE SHAP VALUES
# ==========================================

cost_shap_values = cost_explainer.shap_values(
    X_cost_one_dense
)

delay_shap_values = delay_explainer.shap_values(
    X_delay_one_dense
)

print("Cost SHAP calculated successfully!")
print("Delay SHAP calculated successfully!")

print("\nCost SHAP type:", type(cost_shap_values))
print("Delay SHAP type:", type(delay_shap_values))

Cost SHAP calculated successfully!
Delay SHAP calculated successfully!

Cost SHAP type: <class 'numpy.ndarray'>
Delay SHAP type: <class 'numpy.ndarray'>

In [81]:
# ==========================================
# STEP 5: CHECK SHAP OUTPUT SHAPES
# ==========================================

print("Cost SHAP shape:", cost_shap_values.shape)
print("Delay SHAP shape:", delay_shap_values.shape)

print("\nCost SHAP dimensions:", cost_shap_values.ndim)
print("Delay SHAP dimensions:", delay_shap_values.ndim)

Cost SHAP shape: (1, 212, 2)
Delay SHAP shape: (1, 178, 2)

Cost SHAP dimensions: 3
Delay SHAP dimensions: 3

In [82]:
# ==========================================
# STEP 6: EXTRACT CLASS-1 SHAP VALUES
# ==========================================

# Class 1 = YES
cost_shap_yes = cost_shap_values[0, :, 1]
delay_shap_yes = delay_shap_values[0, :, 1]

print("Cost SHAP values:", cost_shap_yes.shape)
print("Delay SHAP values:", delay_shap_yes.shape)

print("\nCost SHAP range:",
      cost_shap_yes.min(),
      "to",
      cost_shap_yes.max())

print("Delay SHAP range:",
      delay_shap_yes.min(),
      "to",
      delay_shap_yes.max())

Cost SHAP values: (212,)
Delay SHAP values: (178,)

Cost SHAP range: -0.07851643232177258 to 0.010391576478322458
Delay SHAP range: -0.041149311438168225 to 0.026617325100553438

In [83]:
# ==========================================
# STEP 7: GET TRANSFORMED FEATURE NAMES
# ==========================================

cost_feature_names = cost_model.named_steps[
    'preprocessor'
].get_feature_names_out()

delay_feature_names = delay_model.named_steps[
    'preprocessor'
].get_feature_names_out()

print("Cost feature count:", len(cost_feature_names))
print("Delay feature count:", len(delay_feature_names))

print("\nFirst 20 Cost features:")
print(cost_feature_names[:20])

print("\nFirst 20 Delay features:")
print(delay_feature_names[:20])

Cost feature count: 212
Delay feature count: 178

First 20 Cost features:
['num__Original Cost (in cr.)' 'num__Expenditure (in cr.)'
 'num__Physical Progress (in %)' 'num__Planned Duration (days)'
 'num__Expenditure Ratio (%)' 'num__Expenditure-Progress Gap (%)'
 'num__Cost Base Anomaly'
 'cat__Sector Name_Aviation & Aviation Infrastructure'
 'cat__Sector Name_Coal' 'cat__Sector Name_Construction'
 'cat__Sector Name_Education' 'cat__Sector Name_Electricity Generation'
 'cat__Sector Name_Energy Storage' 'cat__Sector Name_Healthcare'
 'cat__Sector Name_Inland Waterways'
 'cat__Sector Name_Logistics Infrastructure'
 'cat__Sector Name_Metals & Mining' 'cat__Sector Name_Oil & Gas'
 'cat__Sector Name_Railways' 'cat__Sector Name_Real Estate']

First 20 Delay features:
['num__Original Cost (in cr.)' 'num__Expenditure (in cr.)'
 'num__Physical Progress (in %)' 'num__Planned Duration (days)'
 'num__Expenditure Ratio (%)' 'num__Expenditure-Progress Gap (%)'
 'num__Cost Base Anomaly'
 'cat__Sector Name_Aviation & Aviation Infrastructure'
 'cat__Sector Name_Coal' 'cat__Sector Name_Education'
 'cat__Sector Name_Electricity Generation'
 'cat__Sector Name_Energy Storage' 'cat__Sector Name_Healthcare'
 'cat__Sector Name_Inland Waterways'
 'cat__Sector Name_Logistics Infrastructure'
 'cat__Sector Name_Metals & Mining' 'cat__Sector Name_Oil & Gas'
 'cat__Sector Name_Railways' 'cat__Sector Name_Real Estate'
 'cat__Sector Name_Roads & Highways']

In [84]:
# ==========================================
# STEP 8: TOP SHAP RISK FACTORS
# ==========================================

import pandas as pd
import numpy as np

# Create SHAP tables
cost_shap_df = pd.DataFrame({
    "Feature": cost_feature_names,
    "SHAP Value": cost_shap_yes
})

delay_shap_df = pd.DataFrame({
    "Feature": delay_feature_names,
    "SHAP Value": delay_shap_yes
})

# Add absolute SHAP value
cost_shap_df["Importance"] = cost_shap_df["SHAP Value"].abs()
delay_shap_df["Importance"] = delay_shap_df["SHAP Value"].abs()

# Sort by importance
cost_top = cost_shap_df.sort_values(
    "Importance", ascending=False
).head(10)

delay_top = delay_shap_df.sort_values(
    "Importance", ascending=False
).head(10)

print("====================================")
print("     TOP COST OVERRUN FACTORS")
print("====================================")
print(cost_top[["Feature", "SHAP Value"]].to_string(index=False))

print("\n====================================")
print("          TOP DELAY FACTORS")
print("====================================")
print(delay_top[["Feature", "SHAP Value"]].to_string(index=False))

====================================
     TOP COST OVERRUN FACTORS
====================================
                                                 Feature  SHAP Value
                         cat__Implementing Agency_NHIDCL   -0.078516
                               num__Expenditure (in cr.)   -0.075422
                           num__Physical Progress (in %)   -0.066966
                           cat__Implementing Agency_NHAI   -0.026047
                             num__Original Cost (in cr.)   -0.024930
                       num__Expenditure-Progress Gap (%)   -0.018879
                 cat__Line Ministry_Ministry of Railways   -0.012326
cat__Line Ministry_Ministry of Road Transport & Highways   -0.011415
                               cat__Sector Name_Railways   -0.011161
                       cat__Sector Name_Roads & Highways   -0.010702

====================================
          TOP DELAY FACTORS
====================================
                                                 Feature  SHAP Value
                           num__Physical Progress (in %)   -0.041149
                               num__Expenditure (in cr.)   -0.034748
                             num__Original Cost (in cr.)    0.026617
                              num__Expenditure Ratio (%)    0.017419
                            num__Planned Duration (days)   -0.015957
                          cat__Implementing Agency_MoRTH   -0.015301
                       cat__Sector Name_Roads & Highways   -0.014353
                         cat__Implementing Agency_NHIDCL   -0.012989
cat__Line Ministry_Ministry of Road Transport & Highways   -0.010870
                               cat__Sector Name_Railways    0.005607

In [85]:
# ==========================================
# STEP 9: CLEAN SHAP FEATURE NAMES
# ==========================================

def clean_feature_name(feature):
    
    # Numerical features
    if feature.startswith("num__"):
        name = feature.replace("num__", "")
        
        replacements = {
            "Original Cost (in cr.)": "Original Cost",
            "Expenditure (in cr.)": "Expenditure",
            "Physical Progress (in %)": "Physical Progress",
            "Planned Duration (days)": "Planned Duration",
            "Expenditure Ratio (%)": "Expenditure Ratio",
            "Expenditure-Progress Gap (%)": "Expenditure-Progress Gap",
            "Cost Base Anomaly": "Cost Base Anomaly"
        }
        
        return replacements.get(name, name)
    
    # Categorical features
    if feature.startswith("cat__"):
        name = feature.replace("cat__", "")
        
        if "_" in name:
            column, value = name.split("_", 1)
            return f"{column}: {value}"
        
        return name
    
    return feature


# Apply cleaning
cost_shap_df["Clean Feature"] = cost_shap_df["Feature"].apply(
    clean_feature_name
)

delay_shap_df["Clean Feature"] = delay_shap_df["Feature"].apply(
    clean_feature_name
)

# Top 10
cost_top_clean = cost_shap_df.sort_values(
    "Importance", ascending=False
).head(10)

delay_top_clean = delay_shap_df.sort_values(
    "Importance", ascending=False
).head(10)


print("====================================")
print("     CLEAN COST SHAP FACTORS")
print("====================================")

print(
    cost_top_clean[
        ["Clean Feature", "SHAP Value"]
    ].to_string(index=False)
)


print("\n====================================")
print("     CLEAN DELAY SHAP FACTORS")
print("====================================")

print(
    delay_top_clean[
        ["Clean Feature", "SHAP Value"]
    ].to_string(index=False)
)

====================================
     CLEAN COST SHAP FACTORS
====================================
                                       Clean Feature  SHAP Value
                         Implementing Agency: NHIDCL   -0.078516
                                         Expenditure   -0.075422
                                   Physical Progress   -0.066966
                           Implementing Agency: NHAI   -0.026047
                                       Original Cost   -0.024930
                            Expenditure-Progress Gap   -0.018879
                 Line Ministry: Ministry of Railways   -0.012326
Line Ministry: Ministry of Road Transport & Highways   -0.011415
                               Sector Name: Railways   -0.011161
                       Sector Name: Roads & Highways   -0.010702

====================================
     CLEAN DELAY SHAP FACTORS
====================================
                                       Clean Feature  SHAP Value
                                   Physical Progress   -0.041149
                                         Expenditure   -0.034748
                                       Original Cost    0.026617
                                   Expenditure Ratio    0.017419
                                    Planned Duration   -0.015957
                          Implementing Agency: MoRTH   -0.015301
                       Sector Name: Roads & Highways   -0.014353
                         Implementing Agency: NHIDCL   -0.012989
Line Ministry: Ministry of Road Transport & Highways   -0.010870
                               Sector Name: Railways    0.005607

In [86]:
# ==========================================
# STEP 10: SHAP RISK EXPLANATION FUNCTION
# ==========================================

def get_shap_explanation(shap_df, top_n=5):

    # Factors increasing risk
    risk_increasing = (
        shap_df[shap_df["SHAP Value"] > 0]
        .sort_values("SHAP Value", ascending=False)
        .head(top_n)
    )

    # Factors reducing risk
    risk_reducing = (
        shap_df[shap_df["SHAP Value"] < 0]
        .sort_values("SHAP Value", ascending=True)
        .head(top_n)
    )

    return risk_increasing, risk_reducing


# Cost explanation
cost_increasing, cost_reducing = get_shap_explanation(
    cost_shap_df
)

# Delay explanation
delay_increasing, delay_reducing = get_shap_explanation(
    delay_shap_df
)


print("====================================")
print("       COST RISK INCREASING")
print("====================================")

print(
    cost_increasing[
        ["Clean Feature", "SHAP Value"]
    ].to_string(index=False)
)


print("\n====================================")
print("       COST RISK REDUCING")
print("====================================")

print(
    cost_reducing[
        ["Clean Feature", "SHAP Value"]
    ].to_string(index=False)
)


print("\n====================================")
print("       DELAY RISK INCREASING")
print("====================================")

print(
    delay_increasing[
        ["Clean Feature", "SHAP Value"]
    ].to_string(index=False)
)


print("\n====================================")
print("       DELAY RISK REDUCING")
print("====================================")

print(
    delay_reducing[
        ["Clean Feature", "SHAP Value"]
    ].to_string(index=False)
)

====================================
       COST RISK INCREASING
====================================
                           Clean Feature  SHAP Value
                        Planned Duration    0.010392
              Implementing Agency: MoRTH    0.008454
                       Sector Name: Coal    0.004802
         Line Ministry: Ministry of Coal    0.004354
Sector Name: Transmission & Distribution    0.001278

====================================
       COST RISK REDUCING
====================================
              Clean Feature  SHAP Value
Implementing Agency: NHIDCL   -0.078516
                Expenditure   -0.075422
          Physical Progress   -0.066966
  Implementing Agency: NHAI   -0.026047
              Original Cost   -0.024930

====================================
       DELAY RISK INCREASING
====================================
                      Clean Feature  SHAP Value
                      Original Cost    0.026617
                  Expenditure Ratio    0.017419
              Sector Name: Railways    0.005607
Line Ministry: Ministry of Railways    0.004667
 Implementing Agency: CAOCWR WR mor    0.001608

====================================
       DELAY RISK REDUCING
====================================
                Clean Feature  SHAP Value
            Physical Progress   -0.041149
                  Expenditure   -0.034748
             Planned Duration   -0.015957
   Implementing Agency: MoRTH   -0.015301
Sector Name: Roads & Highways   -0.014353

In [87]:
# ==========================================
# STEP 11: GENERAL SHAP EXPLANATION
# ==========================================

def explain_project(project):

    # Convert project dictionary to DataFrame
    input_data = pd.DataFrame([project])

    # ---------- COST ----------
    cost_transformed = cost_model.named_steps[
        'preprocessor'
    ].transform(input_data)

    if hasattr(cost_transformed, "toarray"):
        cost_transformed = cost_transformed.toarray()

    cost_transformed = np.asarray(
        cost_transformed,
        dtype=np.float64
    )

    cost_explainer = shap.TreeExplainer(
        cost_model.named_steps['classifier']
    )

    cost_values = cost_explainer.shap_values(
        cost_transformed
    )

    # Class 1 = Cost Overrun YES
    cost_values = cost_values[0, :, 1]

    cost_names = cost_model.named_steps[
        'preprocessor'
    ].get_feature_names_out()

    cost_df = pd.DataFrame({
        "Feature": cost_names,
        "SHAP Value": cost_values
    })

    cost_df["Clean Feature"] = cost_df["Feature"].apply(
        clean_feature_name
    )

    cost_df["Importance"] = cost_df["SHAP Value"].abs()

    # ---------- DELAY ----------
    delay_transformed = delay_model.named_steps[
        'preprocessor'
    ].transform(input_data)

    if hasattr(delay_transformed, "toarray"):
        delay_transformed = delay_transformed.toarray()

    delay_transformed = np.asarray(
        delay_transformed,
        dtype=np.float64
    )

    delay_explainer = shap.TreeExplainer(
        delay_model.named_steps['classifier']
    )

    delay_values = delay_explainer.shap_values(
        delay_transformed
    )

    # Class 1 = Delay YES
    delay_values = delay_values[0, :, 1]

    delay_names = delay_model.named_steps[
        'preprocessor'
    ].get_feature_names_out()

    delay_df = pd.DataFrame({
        "Feature": delay_names,
        "SHAP Value": delay_values
    })

    delay_df["Clean Feature"] = delay_df["Feature"].apply(
        clean_feature_name
    )

    delay_df["Importance"] = delay_df["SHAP Value"].abs()

    # ---------- SEPARATE RISK DRIVERS ----------

    cost_increasing = (
        cost_df[cost_df["SHAP Value"] > 0]
        .sort_values("SHAP Value", ascending=False)
        .head(5)
    )

    cost_reducing = (
        cost_df[cost_df["SHAP Value"] < 0]
        .sort_values("SHAP Value", ascending=True)
        .head(5)
    )

    delay_increasing = (
        delay_df[delay_df["SHAP Value"] > 0]
        .sort_values("SHAP Value", ascending=False)
        .head(5)
    )

    delay_reducing = (
        delay_df[delay_df["SHAP Value"] < 0]
        .sort_values("SHAP Value", ascending=True)
        .head(5)
    )

    return {
        "Cost Risk Drivers": cost_increasing,
        "Cost Risk Reducing Factors": cost_reducing,
        "Delay Risk Drivers": delay_increasing,
        "Delay Risk Reducing Factors": delay_reducing
    }

In [88]:
# ==========================================
# TEST STEP 11
# ==========================================

project = df.iloc[0][prediction_features].to_dict()

explanation = explain_project(project)

print("====================================")
print("       COST RISK DRIVERS")
print("====================================")

print(
    explanation["Cost Risk Drivers"][
        ["Clean Feature", "SHAP Value"]
    ].to_string(index=False)
)

print("\n====================================")
print("       DELAY RISK DRIVERS")
print("====================================")

print(
    explanation["Delay Risk Drivers"][
        ["Clean Feature", "SHAP Value"]
    ].to_string(index=False)
)

====================================
       COST RISK DRIVERS
====================================
                                       Clean Feature  SHAP Value
                          Implementing Agency: MoRTH    0.013497
Line Ministry: Ministry of Road Transport & Highways    0.007796
                         Implementing Agency: NHIDCL    0.006822
                     Line Ministry: Ministry of Coal    0.006056
                                   Sector Name: Coal    0.005845

====================================
       DELAY RISK DRIVERS
====================================
                                       Clean Feature  SHAP Value
                                    Planned Duration    0.070442
                       Sector Name: Roads & Highways    0.047692
Line Ministry: Ministry of Road Transport & Highways    0.041471
     Sector Name: Aviation & Aviation Infrastructure    0.029851
                                   Expenditure Ratio    0.025419

In [89]:
# ==========================================
# STEP 12: FINAL PROJECT RISK ENGINE
# ==========================================

def predict_project_risk(project):

    # Convert project dictionary to DataFrame
    input_data = pd.DataFrame([project])

    # ==========================================
    # 1. COST PREDICTION
    # ==========================================

    cost_probability = cost_model.predict_proba(input_data)[0][1]
    cost_prediction = cost_model.predict(input_data)[0]

    cost_risk = cost_probability * 100


    # ==========================================
    # 2. DELAY PREDICTION
    # ==========================================

    delay_probability = delay_model.predict_proba(input_data)[0][1]
    delay_prediction = delay_model.predict(input_data)[0]

    delay_risk = delay_probability * 100


    # ==========================================
    # 3. OVERALL RISK SCORE
    # ==========================================

    overall_score = (
        0.50 * cost_risk +
        0.50 * delay_risk
    )


    # ==========================================
    # 4. RISK LEVEL
    # ==========================================

    if overall_score < 30:
        risk_level = "LOW"
        warning = "PROJECT APPEARS STABLE"

    elif overall_score < 60:
        risk_level = "MEDIUM"
        warning = "CLOSE MONITORING REQUIRED"

    else:
        risk_level = "HIGH"
        warning = "IMMEDIATE ATTENTION REQUIRED"


    # ==========================================
    # 5. SHAP EXPLANATION
    # ==========================================

    explanation = explain_project(project)


    # ==========================================
    # 6. RETURN EVERYTHING
    # ==========================================

    return {

        "Cost Overrun Probability": round(
            cost_risk, 2
        ),

        "Cost Overrun Prediction":
            "YES" if cost_prediction == 1 else "NO",

        "Delay Probability": round(
            delay_risk, 2
        ),

        "Delay Prediction":
            "YES" if delay_prediction == 1 else "NO",

        "Overall Risk Score": round(
            overall_score, 2
        ),

        "Risk Level": risk_level,

        "Early Warning": warning,

        "Cost Risk Drivers":
            explanation["Cost Risk Drivers"],

        "Cost Risk Reducing Factors":
            explanation["Cost Risk Reducing Factors"],

        "Delay Risk Drivers":
            explanation["Delay Risk Drivers"],

        "Delay Risk Reducing Factors":
            explanation["Delay Risk Reducing Factors"]
    }

In [90]:
# ==========================================
# TEST FINAL RISK ENGINE
# ==========================================

project = df.iloc[0][prediction_features].to_dict()

result = predict_project_risk(project)

print("====================================")
print("       FINAL PROJECT RISK")
print("====================================")

print(
    "Cost Overrun Risk:",
    result["Cost Overrun Probability"],
    "%"
)

print(
    "Cost Overrun Prediction:",
    result["Cost Overrun Prediction"]
)

print(
    "Delay Risk:",
    result["Delay Probability"],
    "%"
)

print(
    "Delay Prediction:",
    result["Delay Prediction"]
)

print(
    "Overall Risk Score:",
    result["Overall Risk Score"],
    "/ 100"
)

print(
    "Risk Level:",
    result["Risk Level"]
)

print(
    "Early Warning:",
    result["Early Warning"]
)

print("\n====================================")
print("       COST RISK DRIVERS")
print("====================================")

print(
    result["Cost Risk Drivers"][
        ["Clean Feature", "SHAP Value"]
    ].to_string(index=False)
)

print("\n====================================")
print("       DELAY RISK DRIVERS")
print("====================================")

print(
    result["Delay Risk Drivers"][
        ["Clean Feature", "SHAP Value"]
    ].to_string(index=False)
)

====================================
       FINAL PROJECT RISK
====================================
Cost Overrun Risk: 24.48 %
Cost Overrun Prediction: NO
Delay Risk: 82.1 %
Delay Prediction: YES
Overall Risk Score: 53.29 / 100
Risk Level: MEDIUM
Early Warning: CLOSE MONITORING REQUIRED

====================================
       COST RISK DRIVERS
====================================
                                       Clean Feature  SHAP Value
                          Implementing Agency: MoRTH    0.013497
Line Ministry: Ministry of Road Transport & Highways    0.007796
                         Implementing Agency: NHIDCL    0.006822
                     Line Ministry: Ministry of Coal    0.006056
                                   Sector Name: Coal    0.005845

====================================
       DELAY RISK DRIVERS
====================================
                                       Clean Feature  SHAP Value
                                    Planned Duration    0.070442
                       Sector Name: Roads & Highways    0.047692
Line Ministry: Ministry of Road Transport & Highways    0.041471
     Sector Name: Aviation & Aviation Infrastructure    0.029851
                                   Expenditure Ratio    0.025419

In [91]:
# ==========================================
# STEP 13: SAVE FINAL MODELS
# ==========================================

import joblib

joblib.dump(cost_model, "cost_model.pkl")
joblib.dump(delay_model, "delay_model.pkl")

print("====================================")
print("       MODELS SAVED SUCCESSFULLY")
print("====================================")
print("cost_model.pkl  saved suceesefull")
print("delay_model saved")

====================================
       MODELS SAVED SUCCESSFULLY
====================================
cost_model.pkl  saved suceesefull
delay_model saved

In [92]:
print("X_test exists:", 'X_test' in globals())
print("y_test exists:", 'y_test' in globals())
print("X_test_cost exists:", 'X_test_cost' in globals())
print("y_test_cost exists:", 'y_test_cost' in globals())
print("X_test_delay exists:", 'X_test_delay' in globals())
print("y_test_delay exists:", 'y_test_delay' in globals())

X_test exists: True
y_test exists: True
X_test_cost exists: False
y_test_cost exists: False
X_test_delay exists: False
y_test_delay exists: False

In [94]:
# cost_results = evaluate_model(
#     cost_model,
#     X_test,
#     y_test,
#     "COST OVERRUN MODEL"
# )

In [95]:
!pip install -r requirements.txt

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: streamlit in c:\programdata\anaconda3\lib\site-packages (from -r requirements.txt (line 1)) (1.51.0)
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (from -r requirements.txt (line 2)) (2.3.3)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from -r requirements.txt (line 3)) (2.3.5)
Requirement already satisfied: scikit-learn in c:\programdata\anaconda3\lib\site-packages (from -r requirements.txt (line 4)) (1.7.2)
Requirement already satisfied: joblib in c:\programdata\anaconda3\lib\site-packages (from -r requirements.txt (line 5)) (1.5.2)
Requirement already satisfied: matplotlib in c:\programdata\anaconda3\lib\site-packages (from -r requirements.txt (line 6)) (3.10.6)
Requirement already satisfied: shap in c:\users\dell\appdata\roaming\python\python313\site-packages (from -r requirements.txt (line 7)) (0.52.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit->-r requirements.txt (line 1)) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit->-r requirements.txt (line 1)) (1.9.0)
Requirement already satisfied: cachetools<7,>=4.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit->-r requirements.txt (line 1)) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit->-r requirements.txt (line 1)) (8.2.1)
Requirement already satisfied: packaging<26,>=20 in c:\programdata\anaconda3\lib\site-packages (from streamlit->-r requirements.txt (line 1)) (25.0)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit->-r requirements.txt (line 1)) (12.0.0)
Requirement already satisfied: protobuf<7,>=3.20 in c:\users\dell\appdata\roaming\python\python313\site-packages (from streamlit->-r requirements.txt (line 1)) (6.33.6)
Requirement already satisfied: pyarrow<22,>=7.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit->-r requirements.txt (line 1)) (21.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\programdata\anaconda3\lib\site-packages (from streamlit->-r requirements.txt (line 1)) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit->-r requirements.txt (line 1)) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in c:\programdata\anaconda3\lib\site-packages (from streamlit->-r requirements.txt (line 1)) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit->-r requirements.txt (line 1)) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\programdata\anaconda3\lib\site-packages (from streamlit->-r requirements.txt (line 1)) (4.0.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\programdata\anaconda3\lib\site-packages (from streamlit->-r requirements.txt (line 1)) (3.1.45)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\programdata\anaconda3\lib\site-packages (from streamlit->-r requirements.txt (line 1)) (6.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas->-r requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas->-r requirements.txt (line 2)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas->-r requirements.txt (line 2)) (2025.2)
Requirement already satisfied: jinja2 in c:\programdata\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit->-r requirements.txt (line 1)) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\programdata\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit->-r requirements.txt (line 1)) (4.25.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\programdata\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit->-r requirements.txt (line 1)) (2.7.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit->-r requirements.txt (line 1)) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\programdata\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit->-r requirements.txt (line 1)) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\programdata\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit->-r requirements.txt (line 1)) (4.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit->-r requirements.txt (line 1)) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit->-r requirements.txt (line 1)) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit->-r requirements.txt (line 1)) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit->-r requirements.txt (line 1)) (2026.5.20)
Requirement already satisfied: scipy>=1.8.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn->-r requirements.txt (line 4)) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn->-r requirements.txt (line 4)) (3.5.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib->-r requirements.txt (line 6)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib->-r requirements.txt (line 6)) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib->-r requirements.txt (line 6)) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib->-r requirements.txt (line 6)) (1.4.9)
Requirement already satisfied: pyparsing>=2.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib->-r requirements.txt (line 6)) (3.2.5)
Requirement already satisfied: tqdm>=4.27.0 in c:\programdata\anaconda3\lib\site-packages (from shap->-r requirements.txt (line 7)) (4.67.1)
Requirement already satisfied: slicer==0.0.8 in c:\users\dell\appdata\roaming\python\python313\site-packages (from shap->-r requirements.txt (line 7)) (0.0.8)
Requirement already satisfied: numba in c:\programdata\anaconda3\lib\site-packages (from shap->-r requirements.txt (line 7)) (0.62.1)
Requirement already satisfied: llvmlite in c:\programdata\anaconda3\lib\site-packages (from shap->-r requirements.txt (line 7)) (0.45.1)
Requirement already satisfied: cloudpickle in c:\programdata\anaconda3\lib\site-packages (from shap->-r requirements.txt (line 7)) (3.1.1)
Requirement already satisfied: attrs>=22.2.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit->-r requirements.txt (line 1)) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit->-r requirements.txt (line 1)) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit->-r requirements.txt (line 1)) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit->-r requirements.txt (line 1)) (0.28.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 2)) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit->-r requirements.txt (line 1)) (3.0.2)

In [96]:
!pip install streamlit pandas numpy scikit-learn joblib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: streamlit in c:\programdata\anaconda3\lib\site-packages (1.51.0)
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: scikit-learn in c:\programdata\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: joblib in c:\programdata\anaconda3\lib\site-packages (1.5.2)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<7,>=4.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (8.2.1)
Requirement already satisfied: packaging<26,>=20 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (25.0)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (12.0.0)
Requirement already satisfied: protobuf<7,>=3.20 in c:\users\dell\appdata\roaming\python\python313\site-packages (from streamlit) (6.33.6)
Requirement already satisfied: pyarrow<22,>=7.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (21.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (4.0.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (3.1.45)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (6.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: jinja2 in c:\programdata\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\programdata\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\programdata\anaconda3\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.7.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\programdata\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\programdata\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2026.5.20)
Requirement already satisfied: scipy>=1.8.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: attrs>=22.2.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.28.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.2)